title: Feroz Khan
#logo: /assets/img/file1.png


description: "Data Scientist | Storyteller | Painter | Passionate about AI/ML, Data Science, and Software Engineering. I love solving problems through data-driven insights and building scalable machine learning models."

description: "Data Scientist | Storyteller | Painter | Passionate about AI/ML, Data Science, and Software Engineering. I love solving problems through data-driven insights and building scalable machine learning models."
#show_downloads: true
theme: jekyll-theme-minimal

