title: Feroz Khan
logo: /assets/img/Feroz1.png


description: I love building AI systems, painting in my free time, and sharing ideas whether through math and code, art, or presentations. 
#show_downloads: true
theme: jekyll-theme-minimal
