title: Feroz Khan
#logo: /assets/img/file1.png


description: Data Scientist | Storyteller | Painter 

This is sa sdgnklsgn
sdgjsdgal
sd
gsdgsd
gsd
gsd
gds
#show_downloads: true
theme: jekyll-theme-minimal
